'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ja' | 'ko' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  getCurrentLanguage: () => Language;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  en: {
    // Header
    'header.title': 'PayMap Japan',
    'header.backToHome': 'Back to Home',
    'header.anonymous': 'Anonymous',
    
    // Search
    'search.placeholder': 'Search for restaurants in Japan...',
    'search.button': 'Search',
    'search.searching': 'Searching...',
    'search.clear': 'Clear',
    'search.clearAll': 'Show original restaurants',
    'search.info': 'You can search for restaurants across all of Japan!',
    'search.examples': 'Examples: "Ramen", "Sushi", "Osaka restaurants", "Tokyo cafes", "Kyoto traditional food", etc.',
    'search.nationwide': 'Search results will be found nationwide in Japan.',
    
    // Filters
    'filters.paymentMethods': 'Payment Methods',
    'filters.advanced': 'Advanced Filters',
    'filters.sort': 'Sort',
    'filters.history': 'History',
    'filters.favorites': 'Favorites',
    'filters.clearAll': 'Clear All Filters',
    'filters.active': 'Active',
    
    // Payment Methods
    'payment.selectMethods': 'Select Payment Methods:',
    
    // Results
    'results.found': 'Found {count} restaurant(s)',
    'results.showing': 'Showing {count} restaurant(s)',
    'results.withSelectedMethods': ' with selected payment methods',
    'results.searchResults': 'Search Results',
    'results.restaurants': 'restaurants',
    'results.nationwideSearch': 'Searched nationwide in Japan',
    'results.filteredByPayment': 'Filtered by selected payment methods',
    'results.backToOriginal': 'Back to original restaurants',
    'results.basicRestaurants': 'Showing {count} basic restaurants',
    
    // Restaurant Info
    'restaurant.paymentMethods': 'Payment Methods',
    'restaurant.reviews': 'Reviews',
    'restaurant.writeReview': 'Write Review',
    'restaurant.noReviews': 'No reviews yet. Be the first to review!',
    'restaurant.noReviewsMessage': 'No reviews have been registered yet. Please participate in writing reviews!',
    'restaurant.noPaymentMethods': 'No payment method information available yet. Add a review to share payment options!',
    'restaurant.searchResult': 'Search Result',
    'restaurant.restaurant': 'Restaurant',
    'restaurant.city': 'City',
    
    // Reviews
    'review.sample': 'Sample review - Add your own review to share actual payment options!',
    'review.delete': 'Delete',
    'review.helpful': '👍',
    
    // Advanced Filters
    'advancedFilters.title': 'Advanced Filters',
    'advancedFilters.priceRange': 'Price Range',
    'advancedFilters.rating': 'Minimum Rating',
    'advancedFilters.distance': 'Distance (km)',
    'advancedFilters.openNow': 'Open Now',
    'advancedFilters.hasReviews': 'Has Reviews',
    'advancedFilters.paymentMethods': 'Payment Methods',
    'advancedFilters.clearAll': 'Clear All',
    'advancedFilters.apply': 'Apply Filters',
    
    // Sort Options
    'sort.title': 'Sort Options',
    'sort.rating': 'Rating',
    'sort.reviewCount': 'Reviews',
    'sort.distance': 'Distance',
    'sort.name': 'Name',
    'sort.newest': 'Newest',
    'sort.ascending': 'Ascending',
    'sort.descending': 'Descending',
    
    // Search History
    'history.title': 'Search History',
    'history.noHistory': 'No search history yet',
    'history.noHistoryDesc': 'Your recent searches will appear here',
    'history.recentSearches': 'recent searches',
    'history.clearAll': 'Clear All',
    'history.justNow': 'Just now',
    'history.minutesAgo': '{count}m ago',
    'history.hoursAgo': '{count}h ago',
    'history.daysAgo': '{count}d ago',
    'history.locationSaved': 'Location saved',
    
    // Favorites
    'favorites.title': 'My Favorites',
    'favorites.noFavorites': 'No favorites yet',
    'favorites.noFavoritesDesc': 'Add restaurants to your favorites to see them here',
    'favorites.view': 'View',
    'favorites.addNote': 'Add Note',
    'favorites.editNote': 'Edit Note',
    'favorites.save': 'Save',
    'favorites.cancel': 'Cancel',
    'favorites.noNote': 'No note added',
    'favorites.added': 'Added',
    'favorites.today': 'Today',
    'favorites.yesterday': 'Yesterday',
    'favorites.daysAgo': '{count} days ago',
    'favorites.clearAll': 'Clear All',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.view': 'View',
    'common.clear': 'Clear',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.favorites': 'Favorites',
    'common.history': 'History',
    'common.settings': 'Settings',
    'common.language': 'Language',
    'common.theme': 'Theme',
    'common.darkMode': 'Dark Mode',
    'common.lightMode': 'Light Mode',
    'common.system': 'System',
    
    // Main page
    'paymentMethodReviewService': 'Payment Method Review Service',
    'discoverPaymentMethods': 'Discover Payment Methods at Japanese Restaurants',
    'heroDescription': 'Find restaurants on Google Maps, check available payment methods, and share your experiences with others',
    'viewMap': 'View Map',
    'writeReview': 'Write Review',
    'mapBasedSearch': 'Map-Based Search',
    'mapBasedSearchDesc': 'Easily find restaurants in your desired area and check their locations on Google Maps',
    'paymentMethodInfo': 'Payment Method Info',
    'paymentMethodInfoDesc': 'Check available payment methods at each restaurant at a glance',
    'realTimeReviews': 'Real-time Reviews',
    'realTimeReviewsDesc': 'Leave anonymous reviews about payment methods and share them with others',
    'howToUse': 'How to Use',
    'findRestaurants': 'Find Restaurants',
    'findRestaurantsDesc': 'Browse the map to find restaurants in your desired area',
    'clickMarker': 'Click Marker',
    'clickMarkerDesc': 'Click on restaurant markers to view detailed information',
    'checkPayment': 'Check Payment',
    'checkPaymentDesc': 'View available payment methods and other people\'s reviews',
    'writeReviewDesc': 'Share your experience by writing a review',
    
    // Content Filtering
    'contentFilter.title': 'Content Validation Result',
    'contentFilter.violations': 'Detected Issues:',
    'contentFilter.warning': 'Warning:',
    'contentFilter.filteredText': 'Filtered Text:',
    'contentFilter.inappropriateLanguage': 'Inappropriate Language Usage',
    'contentFilter.advertising': 'Advertising Content',
    'contentFilter.sensitiveTopic': 'Sensitive Topic Mention',
    'contentFilter.spam': 'Spam Content',
    'contentFilter.tooShort': 'Review too short',
    'contentFilter.tooLong': 'Review too long',
    'contentFilter.paymentKeywords': 'Please include content related to payment methods.',
    
    // Map Controls
    'map.zoomIn': 'Zoom In',
    'map.zoomOut': 'Zoom Out',
    'map.currentLocation': 'Go to current location',
    'map.locationDetecting': 'Detecting location...',
    'map.currentLocationSuccess': 'Current location',
    'map.kyotoDefault': 'Kyoto (Default)',
    'map.showSearchResults': 'Show search results',
    'map.hideSearchResults': 'Hide search results',
    
    // Guide Page
    'guide.title': 'Service Guide',
    'guide.introduction.title': 'Service Introduction',
    'guide.introduction.description': 'Japan Food Web is a service that allows you to check available payment methods at restaurants during your trip to Japan. We provide information about various payment methods such as Suica, PayPay, credit cards, and cash to help you have a convenient trip to Japan.',
    'guide.howToUse.title': 'How to Use',
    'guide.step1.title': 'Search Restaurants',
    'guide.step1.description': 'Find the area you want on the map or enter the restaurant name in the search box.',
    'guide.step1.example': 'Examples: "Ramen", "Sushi", "Osaka restaurants"',
    'guide.step2.title': 'Filter Payment Methods',
    'guide.step2.description': 'Select your desired payment methods to show only restaurants that support those payment methods.',
    'guide.step2.example': 'Examples: Suica, PayPay, Credit Card',
    'guide.step3.title': 'Select Restaurant',
    'guide.step3.description': 'Click on the restaurant you want from the map or list to view detailed information.',
    'guide.step3.example': 'Check payment methods, reviews, ratings',
    'guide.step4.title': 'Write Review',
    'guide.step4.description': 'Share payment method information from visited restaurants with other users.',
    'guide.step4.example': 'Write reviews safely and anonymously',
    'guide.features.title': 'Key Features',
    'guide.features.favorites.title': 'Favorites',
    'guide.features.favorites.description': 'Save frequently visited restaurants to favorites for quick access.',
    'guide.features.history.title': 'Search History',
    'guide.features.history.description': 'Check previous search history to find them again.',
    'guide.features.payment.title': 'Payment Method Information',
    'guide.features.payment.description': 'Provides accurate payment method information based on actual user reviews.',
    'guide.tips.title': 'Usage Tips',
    'guide.tips.tip1': 'When searching, it\'s more effective to search by food type or region name rather than restaurant name.',
    'guide.tips.tip2': 'When selecting multiple payment methods, only restaurants that support all those payment methods will be displayed.',
    'guide.tips.tip3': 'When writing reviews, please select only the payment methods you actually used to provide accurate information.',
    'guide.tips.tip4': 'On mobile, zoom in/out on the map to explore the area you want in detail.',
    'guide.contact.title': 'Contact Us',
    'guide.contact.description': 'If you have any questions while using the service, please contact us anytime.',
    'guide.contact.button': 'Contact Us',
    'guide.contact.start': 'Start Service',
    
    // Privacy Page
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last Updated',
    'privacy.introduction.title': 'Privacy Policy',
    'privacy.introduction.description': 'Japan Food Web strives to protect user privacy. This privacy policy explains how personal information collected when using the service is processed.',
    'privacy.collection.title': 'Information We Collect',
    'privacy.collection.personalInfo.title': 'Personal Information',
    'privacy.collection.personalInfo.item1': 'Anonymous ID (automatically generated via cookies)',
    'privacy.collection.personalInfo.item2': 'Language settings (optional)',
    'privacy.collection.personalInfo.item3': 'Search history (optional)',
    'privacy.collection.usageInfo.title': 'Usage Information',
    'privacy.collection.usageInfo.item1': 'Restaurant search history',
    'privacy.collection.usageInfo.item2': 'Review content',
    'privacy.collection.usageInfo.item3': 'Service usage statistics',
    'privacy.usage.title': 'Purpose of Information Use',
    'privacy.usage.item1': 'Service provision and improvement',
    'privacy.usage.item2': 'User experience enhancement',
    'privacy.usage.item3': 'Restaurant information provision',
    'privacy.usage.item4': 'Review system operation',
    'privacy.usage.item5': 'Service statistics analysis',
    'privacy.protection.title': 'Information Protection',
    'privacy.protection.item1': 'Secure data transmission through SSL encryption',
    'privacy.protection.item2': 'Collection and storage of only anonymized data',
    'privacy.protection.item3': 'Minimization of personal identification information collection',
    'privacy.protection.item4': 'Regular security checks and updates',
    'privacy.thirdParty.title': 'Third-Party Services',
    'privacy.thirdParty.google.title': 'Google Maps API',
    'privacy.thirdParty.google.description': 'We use Google Maps API to provide map services. Google\'s privacy policy applies.',
    'privacy.thirdParty.vercel.title': 'Vercel',
    'privacy.thirdParty.vercel.description': 'We use Vercel for website hosting. Vercel\'s privacy policy applies.',
    'privacy.thirdParty.redis.title': 'Upstash Redis',
    'privacy.thirdParty.redis.description': 'We use Upstash Redis for storing review data. Upstash\'s privacy policy applies.',
    'privacy.rights.title': 'User Rights',
    'privacy.rights.item1': 'Withdrawal of consent for personal information collection and use',
    'privacy.rights.item2': 'Request for access and correction of personal information',
    'privacy.rights.item3': 'Request for deletion of personal information',
    'privacy.rights.item4': 'Request for suspension of personal information processing',
    'privacy.contact.title': 'Contact Information',
    'privacy.contact.email': 'Email',
    'privacy.contact.description': 'If you have any questions regarding privacy, please contact us anytime.',
    'privacy.changes.title': 'Privacy Policy Changes',
    'privacy.changes.description': 'The privacy policy may be added, deleted, or modified according to changes in laws, policies, or security technologies. Changes will be announced on the website.',
    'privacy.navigation.guide': 'User Guide',
    'privacy.navigation.contact': 'Contact Us',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'If you have any questions while using the service, please contact us anytime.',
    'contact.info.title': 'Contact Information',
    'contact.info.email.title': 'Email Inquiry',
    'contact.info.email.description': 'This is the fastest and most accurate way to get a response.',
    'contact.info.response.title': 'Response Time',
    'contact.info.response.description': 'We respond within 24 hours on weekdays and within 48 hours on weekends.',
    'contact.info.hours.title': 'Service Hours',
    'contact.info.hours.description': 'You can contact us 24/7 anytime.',
    'contact.form.title': 'Contact Us',
    'contact.form.email.title': 'Contact by Email',
    'contact.form.email.description': 'Click the button below to automatically open the email composition screen.',
    'contact.form.email.button': 'Send Email',
    'contact.form.email.sent': 'Email app has opened. Please write your inquiry.',
    'contact.form.template.title': 'Inquiry Template',
    'contact.form.template.subject': 'Subject',
    'contact.form.template.body': 'Content',
    'contact.email.subject': '[Japan Food Web] Service Inquiry',
    'contact.email.body': 'Hello.\n\nI am contacting you regarding an inquiry while using the Japan Food Web service.\n\nInquiry Type: [Bug Report / Feature Suggestion / Other]\nInquiry Content:\n\n\nThank you.',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.q1.question': 'Q. Can anyone write reviews?',
    'contact.faq.q1.answer': 'Yes, you can write reviews anonymously without registration. You can safely use the service through anonymous ID.',
    'contact.faq.q2.question': 'Q. What should I do if there is incorrect information?',
    'contact.faq.q2.answer': 'If there are errors in restaurant information, please let us know through the contact form and we will fix them quickly. We also provide accurate information through other users\' reviews.',
    'contact.faq.q3.question': 'Q. Can I use it on mobile?',
    'contact.faq.q3.answer': 'Yes, you can use it conveniently with an optimized interface on mobile browsers. It works smoothly on all devices with responsive design.',
    'contact.faq.q4.question': 'Q. Is personal information safely protected?',
    'contact.faq.q4.answer': 'Yes, we do not collect personal identification information and only use anonymized data. We securely transmit and store data through SSL encryption.',
    'contact.navigation.guide': 'User Guide',
    'contact.navigation.privacy': 'Privacy Policy',
  },
  ja: {
    // Header
    'header.title': 'PayMap Japan',
    'header.backToHome': 'ホームに戻る',
    'header.anonymous': '匿名',
    
    // Search
    'search.placeholder': 'Search for restaurants in Japan...',
    'search.button': '検索',
    'search.searching': '検索中...',
    'search.clear': 'クリア',
    'search.clearAll': '元のレストランを表示',
    'search.info': '日本全国のレストランを検索できます！',
    'search.examples': '例：「ラーメン」「寿司」「大阪 レストラン」「東京 カフェ」「京都 伝統料理」など',
    'search.nationwide': '検索結果は日本全国から見つかります。',
    
    // Filters
    'filters.paymentMethods': '決済方法',
    'filters.advanced': '詳細フィルター',
    'filters.sort': '並び替え',
    'filters.history': '履歴',
    'filters.favorites': 'お気に入り',
    'filters.clearAll': 'すべてのフィルターをクリア',
    'filters.active': 'アクティブ',
    
    // Payment Methods
    'payment.selectMethods': '決済方法を選択:',
    
    // Results
    'results.found': '{count}件のレストランが見つかりました',
    'results.showing': '{count}件のレストランを表示中',
    'results.withSelectedMethods': '選択された決済方法で',
    'results.searchResults': '検索結果',
    'results.restaurants': '件のレストラン',
    'results.nationwideSearch': '日本全国で検索されました',
    'results.filteredByPayment': '選択された決済方法でフィルタリングされました',
    'results.backToOriginal': '元のレストランに戻る',
    'results.basicRestaurants': '基本レストラン{count}件を表示中',
    
    // Restaurant Info
    'restaurant.paymentMethods': '決済方法',
    'restaurant.reviews': 'レビュー',
    'restaurant.writeReview': 'レビューを書く',
    'restaurant.noReviews': 'まだレビューがありません。最初のレビューを書いてみましょう！',
    'restaurant.noReviewsMessage': 'まだ登録されたレビューがありません。レビュー作成にご参加ください！',
    'restaurant.noPaymentMethods': 'まだ決済方法の情報がありません。レビューを追加して決済オプションを共有しましょう！',
    'restaurant.searchResult': '検索結果',
    'restaurant.restaurant': 'レストラン',
    'restaurant.city': '都市',
    
    // Reviews
    'review.sample': 'サンプルレビュー - 実際の決済オプションを共有するには、独自のレビューを追加してください！',
    'review.delete': '削除',
    'review.helpful': '👍',
    
    // Advanced Filters
    'advancedFilters.title': '詳細フィルター',
    'advancedFilters.priceRange': '価格帯',
    'advancedFilters.rating': '最低評価',
    'advancedFilters.distance': '距離 (km)',
    'advancedFilters.openNow': '営業中',
    'advancedFilters.hasReviews': 'レビューあり',
    'advancedFilters.paymentMethods': '決済方法',
    'advancedFilters.clearAll': 'すべてクリア',
    'advancedFilters.apply': 'フィルターを適用',
    
    // Sort Options
    'sort.title': '並び替えオプション',
    'sort.rating': '評価',
    'sort.reviewCount': 'レビュー数',
    'sort.distance': '距離',
    'sort.name': '名前',
    'sort.newest': '最新',
    'sort.ascending': '昇順',
    'sort.descending': '降順',
    
    // Search History
    'history.title': '検索履歴',
    'history.noHistory': 'まだ検索履歴がありません',
    'history.noHistoryDesc': '最近の検索がここに表示されます',
    'history.recentSearches': '件の最近の検索',
    'history.clearAll': 'すべてクリア',
    'history.justNow': '今',
    'history.minutesAgo': '{count}分前',
    'history.hoursAgo': '{count}時間前',
    'history.daysAgo': '{count}日前',
    'history.locationSaved': '位置情報保存済み',
    
    // Favorites
    'favorites.title': 'お気に入り',
    'favorites.noFavorites': 'まだお気に入りがありません',
    'favorites.noFavoritesDesc': 'レストランをお気に入りに追加すると、ここに表示されます',
    'favorites.view': '表示',
    'favorites.addNote': 'メモを追加',
    'favorites.editNote': 'メモを編集',
    'favorites.save': '保存',
    'favorites.cancel': 'キャンセル',
    'favorites.noNote': 'メモが追加されていません',
    'favorites.added': '追加日',
    'favorites.today': '今日',
    'favorites.yesterday': '昨日',
    'favorites.daysAgo': '{count}日前',
    'favorites.clearAll': 'すべてクリア',
    
    // Common
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.close': '閉じる',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.add': '追加',
    'common.view': '表示',
    'common.clear': 'クリア',
    'common.apply': '適用',
    'common.reset': 'リセット',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.sort': '並び替え',
    'common.favorites': 'お気に入り',
    'common.history': '履歴',
    'common.settings': '設定',
    'common.language': '言語',
    'common.theme': 'テーマ',
    'common.darkMode': 'ダークモード',
    'common.lightMode': 'ライトモード',
    'common.system': 'システム',
    
    // Main page
    'paymentMethodReviewService': '決済方法レビューサービス',
    'discoverPaymentMethods': '日本のレストランの決済方法を発見しよう',
    'heroDescription': 'Googleマップでレストランを見つけ、利用可能な決済方法を確認し、他の人と経験を共有しましょう',
    'viewMap': '地図を見る',
    'writeReview': 'レビューを書く',
    'mapBasedSearch': '地図ベース検索',
    'mapBasedSearchDesc': '希望するエリアのレストランを簡単に見つけ、Googleマップで場所を確認できます',
    'paymentMethodInfo': '決済方法情報',
    'paymentMethodInfoDesc': '各レストランで利用可能な決済方法を一目で確認できます',
    'realTimeReviews': 'リアルタイムレビュー',
    'realTimeReviewsDesc': '決済方法について匿名レビューを残し、他の人と共有しましょう',
    'howToUse': '使い方',
    'findRestaurants': 'レストランを見つける',
    'findRestaurantsDesc': '地図を閲覧して、希望するエリアのレストランを見つけましょう',
    'clickMarker': 'マーカーをクリック',
    'clickMarkerDesc': 'レストランマーカーをクリックして詳細情報を確認しましょう',
    'checkPayment': '決済方法確認',
    'checkPaymentDesc': '利用可能な決済方法と他の人のレビューを確認しましょう',
    'writeReviewDesc': 'レビューを書いて経験を共有しましょう',
    
    // Content Filtering
    'contentFilter.title': 'コンテンツ検証結果',
    'contentFilter.violations': '発見された問題点:',
    'contentFilter.warning': '注意事項:',
    'contentFilter.filteredText': 'フィルタリングされたテキスト:',
    'contentFilter.inappropriateLanguage': '不適切な言語使用',
    'contentFilter.advertising': '広告性コンテンツ',
    'contentFilter.sensitiveTopic': 'センシティブな話題言及',
    'contentFilter.spam': 'スパム性コンテンツ',
    'contentFilter.tooShort': 'レビューが短すぎる',
    'contentFilter.tooLong': 'レビューが長すぎる',
    'contentFilter.paymentKeywords': '決済方法に関連する内容を含めてください。',
    
    // Map Controls
    'map.zoomIn': '拡大',
    'map.zoomOut': '縮小',
    'map.currentLocation': '現在地に移動',
    'map.locationDetecting': '位置情報を検出中...',
    'map.currentLocationSuccess': '現在地',
    'map.kyotoDefault': '京都（デフォルト）',
    'map.showSearchResults': '検索結果を表示',
    'map.hideSearchResults': '検索結果を非表示',
    
    // Guide Page
    'guide.title': 'サービス利用ガイド',
    'guide.introduction.title': 'サービス紹介',
    'guide.introduction.description': 'Japan Food Webは、日本旅行中にレストランで利用可能な決済方法を事前に確認できるサービスです。Suica、PayPay、クレジットカード、現金など様々な決済方法の情報を提供し、便利な日本旅行をお手伝いします。',
    'guide.howToUse.title': '使い方',
    'guide.step1.title': 'レストラン検索',
    'guide.step1.description': '地図で希望の地域を探すか、検索ボックスにレストラン名を入力してください。',
    'guide.step1.example': '例：「ラーメン」、「寿司」、「大阪レストラン」',
    'guide.step2.title': '決済方法フィルタリング',
    'guide.step2.description': '希望の決済方法を選択して、その決済方法をサポートするレストランのみを表示してください。',
    'guide.step2.example': '例：Suica、PayPay、クレジットカード',
    'guide.step3.title': 'レストラン選択',
    'guide.step3.description': '地図やリストから希望のレストランをクリックして詳細情報を確認してください。',
    'guide.step3.example': '決済方法、レビュー、評価を確認',
    'guide.step4.title': 'レビュー作成',
    'guide.step4.description': '訪問したレストランの決済方法情報を他のユーザーと共有してください。',
    'guide.step4.example': '匿名で安全にレビューを作成',
    'guide.features.title': '主な機能',
    'guide.features.favorites.title': 'お気に入り',
    'guide.features.favorites.description': 'よく行くレストランをお気に入りに保存して素早くアクセスしてください。',
    'guide.features.history.title': '検索履歴',
    'guide.features.history.description': '以前の検索履歴を確認して再び探してください。',
    'guide.features.payment.title': '決済方法情報',
    'guide.features.payment.description': '実際のユーザーレビューに基づいた正確な決済方法情報を提供します。',
    'guide.tips.title': '使用のコツ',
    'guide.tips.tip1': '検索する際は、レストラン名よりも料理の種類や地域名で検索する方が効果的です。',
    'guide.tips.tip2': '複数の決済方法を選択すると、それらの決済方法をすべてサポートするレストランのみが表示されます。',
    'guide.tips.tip3': 'レビューを作成する際は、実際に使用した決済方法のみを選択して正確な情報を提供してください。',
    'guide.tips.tip4': 'モバイルでは地図を拡大/縮小して希望の地域を詳しく見てください。',
    'guide.contact.title': 'お問い合わせ',
    'guide.contact.description': 'サービス利用中にご不明な点がございましたら、いつでもお問い合わせください。',
    'guide.contact.button': 'お問い合わせ',
    'guide.contact.start': 'サービス開始',
    
    // Privacy Page
    'privacy.title': 'プライバシーポリシー',
    'privacy.lastUpdated': '最終更新',
    'privacy.introduction.title': 'プライバシーポリシー',
    'privacy.introduction.description': 'Japan Food Webは、ユーザーのプライバシーを保護するために最善を尽くしています。このプライバシーポリシーは、サービス利用時に収集される個人情報の処理方法を説明します。',
    'privacy.collection.title': '収集する情報',
    'privacy.collection.personalInfo.title': '個人情報',
    'privacy.collection.personalInfo.item1': '匿名ID（クッキーによる自動生成）',
    'privacy.collection.personalInfo.item2': '言語設定（オプション）',
    'privacy.collection.personalInfo.item3': '検索履歴（オプション）',
    'privacy.collection.usageInfo.title': '使用情報',
    'privacy.collection.usageInfo.item1': 'レストラン検索履歴',
    'privacy.collection.usageInfo.item2': 'レビュー作成内容',
    'privacy.collection.usageInfo.item3': 'サービス利用統計',
    'privacy.usage.title': '情報使用目的',
    'privacy.usage.item1': 'サービス提供及び改善',
    'privacy.usage.item2': 'ユーザー体験向上',
    'privacy.usage.item3': 'レストラン情報提供',
    'privacy.usage.item4': 'レビューシステム運営',
    'privacy.usage.item5': 'サービス統計分析',
    'privacy.protection.title': '情報保護',
    'privacy.protection.item1': 'SSL暗号化による安全なデータ送信',
    'privacy.protection.item2': '匿名化されたデータのみ収集・保存',
    'privacy.protection.item3': '個人識別情報収集の最小化',
    'privacy.protection.item4': '定期的なセキュリティチェック及び更新',
    'privacy.thirdParty.title': '第三者サービス',
    'privacy.thirdParty.google.title': 'Google Maps API',
    'privacy.thirdParty.google.description': '地図サービス提供のためにGoogle Maps APIを使用します。Googleのプライバシーポリシーが適用されます。',
    'privacy.thirdParty.vercel.title': 'Vercel',
    'privacy.thirdParty.vercel.description': 'ウェブサイトホスティングのためにVercelを使用します。Vercelのプライバシーポリシーが適用されます。',
    'privacy.thirdParty.redis.title': 'Upstash Redis',
    'privacy.thirdParty.redis.description': 'レビューデータ保存のためにUpstash Redisを使用します。Upstashのプライバシーポリシーが適用されます。',
    'privacy.rights.title': 'ユーザー権利',
    'privacy.rights.item1': '個人情報収集・利用に関する同意撤回',
    'privacy.rights.item2': '個人情報閲覧・訂正請求',
    'privacy.rights.item3': '個人情報削除請求',
    'privacy.rights.item4': '個人情報処理停止請求',
    'privacy.contact.title': 'お問い合わせ先',
    'privacy.contact.email': 'メール',
    'privacy.contact.description': 'プライバシーに関するご質問がございましたら、いつでもお問い合わせください。',
    'privacy.changes.title': 'プライバシーポリシー変更',
    'privacy.changes.description': 'プライバシーポリシーは、法令、政策、またはセキュリティ技術の変更に応じて内容の追加、削除、修正が行われる場合があります。変更事項はウェブサイトでお知らせします。',
    'privacy.navigation.guide': '利用ガイド',
    'privacy.navigation.contact': 'お問い合わせ',
    
    // Contact Page
    'contact.title': 'お問い合わせ',
    'contact.subtitle': 'サービス利用中にご不明な点がございましたら、いつでもお問い合わせください。',
    'contact.info.title': '連絡先情報',
    'contact.info.email.title': 'メールお問い合わせ',
    'contact.info.email.description': '最も迅速で正確な回答を受けられる方法です。',
    'contact.info.response.title': '回答時間',
    'contact.info.response.description': '平日24時間以内、週末48時間以内に回答いたします。',
    'contact.info.hours.title': 'サービス時間',
    'contact.info.hours.description': '24時間いつでもお問い合わせいただけます。',
    'contact.form.title': 'お問い合わせ',
    'contact.form.email.title': 'メールでお問い合わせ',
    'contact.form.email.description': '下のボタンをクリックすると自動的にメール作成画面が開きます。',
    'contact.form.email.button': 'メール送信',
    'contact.form.email.sent': 'メールアプリが開きました。お問い合わせ内容を記入してください。',
    'contact.form.template.title': 'お問い合わせテンプレート',
    'contact.form.template.subject': '件名',
    'contact.form.template.body': '内容',
    'contact.email.subject': '[Japan Food Web] サービスお問い合わせ',
    'contact.email.body': 'こんにちは。\n\nJapan Food Webサービス利用中にお問い合わせがあり、ご連絡いたします。\n\nお問い合わせ種別：[バグ報告 / 機能提案 / その他]\nお問い合わせ内容：\n\n\nありがとうございます。',
    'contact.faq.title': 'よくある質問',
    'contact.faq.q1.question': 'Q. 誰でもレビューを書けますか？',
    'contact.faq.q1.answer': 'はい、登録なしでも匿名でレビューを書くことができます。匿名IDを通じて安全にサービスをご利用いただけます。',
    'contact.faq.q2.question': 'Q. 間違った情報がある場合はどうすればよいですか？',
    'contact.faq.q2.answer': 'レストラン情報に誤りがある場合は、お問い合わせを通じてお知らせいただければ迅速に修正いたします。また、他のユーザーのレビューを通じて正確な情報を提供します。',
    'contact.faq.q3.question': 'Q. モバイルでも使用できますか？',
    'contact.faq.q3.answer': 'はい、モバイルブラウザでも最適化されたインターフェースで便利にご利用いただけます。レスポンシブデザインで全てのデバイスでスムーズに動作します。',
    'contact.faq.q4.question': 'Q. 個人情報は安全に保護されますか？',
    'contact.faq.q4.answer': 'はい、個人識別情報は収集せず、匿名化されたデータのみを使用します。SSL暗号化を通じて安全にデータを送信・保存します。',
    'contact.navigation.guide': '利用ガイド',
    'contact.navigation.privacy': 'プライバシーポリシー',
  },
  ko: {
    // Header
    'header.title': 'PayMap Japan',
    'header.backToHome': '홈으로 돌아가기',
    'header.anonymous': '익명',
    
    // Search
    'search.placeholder': 'Search for restaurants in Japan...',
    'search.button': '검색',
    'search.searching': '검색 중...',
    'search.clear': '지우기',
    'search.clearAll': '원래 레스토랑 표시',
    'search.info': '일본 전체 지역의 식당을 검색할 수 있습니다!',
    'search.examples': '예시: "라멘", "스시", "오사카 음식점", "도쿄 카페", "교토 전통음식" 등',
    'search.nationwide': '검색 결과는 일본 전역에서 찾아집니다.',
    
    // Filters
    'filters.paymentMethods': '결제 방법',
    'filters.advanced': '고급 필터',
    'filters.sort': '정렬',
    'filters.history': '기록',
    'filters.favorites': '즐겨찾기',
    'filters.clearAll': '모든 필터 지우기',
    'filters.active': '활성',
    
    // Payment Methods
    'payment.selectMethods': '결제 방법 선택:',
    
    // Results
    'results.found': '{count}개의 레스토랑을 찾았습니다',
    'results.showing': '{count}개의 레스토랑을 표시 중',
    'results.withSelectedMethods': '선택된 결제 방법으로',
    'results.searchResults': '검색 결과',
    'results.restaurants': '개 식당',
    'results.nationwideSearch': '일본 전체 지역에서 검색됨',
    'results.filteredByPayment': '선택된 결제수단으로 필터링됨',
    'results.backToOriginal': '기본 식당으로 돌아가기',
    'results.basicRestaurants': '기본 식당 {count}개 표시 중',
    
    // Restaurant Info
    'restaurant.paymentMethods': '결제 방법',
    'restaurant.reviews': '리뷰',
    'restaurant.writeReview': '리뷰 작성',
    'restaurant.noReviews': '아직 리뷰가 없습니다. 첫 번째 리뷰를 작성해보세요!',
    'restaurant.noReviewsMessage': '아직 등록된 리뷰가 없습니다. 리뷰 작성에 참여해주세요!',
    'restaurant.noPaymentMethods': '아직 결제수단 정보가 없습니다. 리뷰를 추가하여 결제 옵션을 공유해주세요!',
    'restaurant.searchResult': '검색 결과',
    'restaurant.restaurant': '식당',
    'restaurant.city': '도시',
    
    // Reviews
    'review.sample': '샘플 리뷰 - 실제 결제 옵션을 공유하려면 자체 리뷰를 추가하세요!',
    'review.delete': '삭제',
    'review.helpful': '👍',
    
    // Advanced Filters
    'advancedFilters.title': '고급 필터',
    'advancedFilters.priceRange': '가격대',
    'advancedFilters.rating': '최소 평점',
    'advancedFilters.distance': '거리 (km)',
    'advancedFilters.openNow': '영업 중',
    'advancedFilters.hasReviews': '리뷰 있음',
    'advancedFilters.paymentMethods': '결제 방법',
    'advancedFilters.clearAll': '모두 지우기',
    'advancedFilters.apply': '필터 적용',
    
    // Sort Options
    'sort.title': '정렬 옵션',
    'sort.rating': '평점',
    'sort.reviewCount': '리뷰 수',
    'sort.distance': '거리',
    'sort.name': '이름',
    'sort.newest': '최신',
    'sort.ascending': '오름차순',
    'sort.descending': '내림차순',
    
    // Search History
    'history.title': '검색 기록',
    'history.noHistory': '아직 검색 기록이 없습니다',
    'history.noHistoryDesc': '최근 검색이 여기에 표시됩니다',
    'history.recentSearches': '개의 최근 검색',
    'history.clearAll': '모두 지우기',
    'history.justNow': '방금',
    'history.minutesAgo': '{count}분 전',
    'history.hoursAgo': '{count}시간 전',
    'history.daysAgo': '{count}일 전',
    'history.locationSaved': '위치 저장됨',
    
    // Favorites
    'favorites.title': '즐겨찾기',
    'favorites.noFavorites': '아직 즐겨찾기가 없습니다',
    'favorites.noFavoritesDesc': '레스토랑을 즐겨찾기에 추가하면 여기에 표시됩니다',
    'favorites.view': '보기',
    'favorites.addNote': '메모 추가',
    'favorites.editNote': '메모 편집',
    'favorites.save': '저장',
    'favorites.cancel': '취소',
    'favorites.noNote': '메모가 추가되지 않았습니다',
    'favorites.added': '추가된 날짜',
    'favorites.today': '오늘',
    'favorites.yesterday': '어제',
    'favorites.daysAgo': '{count}일 전',
    'favorites.clearAll': '모두 지우기',
    
    // Common
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.success': '성공',
    'common.close': '닫기',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.delete': '삭제',
    'common.edit': '편집',
    'common.add': '추가',
    'common.view': '보기',
    'common.clear': '지우기',
    'common.apply': '적용',
    'common.reset': '초기화',
    'common.search': '검색',
    'common.filter': '필터',
    'common.sort': '정렬',
    'common.favorites': '즐겨찾기',
    'common.history': '기록',
    'common.settings': '설정',
    'common.language': '언어',
    'common.theme': '테마',
    'common.darkMode': '다크 모드',
    'common.lightMode': '라이트 모드',
    'common.system': '시스템',
    
    // Main page
    'paymentMethodReviewService': '결제 수단 리뷰 서비스',
    'discoverPaymentMethods': '일본 레스토랑의 결제 수단을 발견하세요',
    'heroDescription': 'Google 지도에서 레스토랑을 찾고, 사용 가능한 결제 수단을 확인하고, 다른 사람들과 경험을 공유하세요',
    'viewMap': '지도 보기',
    'writeReview': '리뷰 작성',
    'mapBasedSearch': '지도 기반 검색',
    'mapBasedSearchDesc': '원하는 지역의 레스토랑을 쉽게 찾고 Google 지도에서 위치를 확인하세요',
    'paymentMethodInfo': '결제 수단 정보',
    'paymentMethodInfoDesc': '각 레스토랑에서 사용 가능한 결제 수단을 한눈에 확인하세요',
    'realTimeReviews': '실시간 리뷰',
    'realTimeReviewsDesc': '결제 수단에 대한 익명 리뷰를 남기고 다른 사람들과 공유하세요',
    'howToUse': '사용 방법',
    'findRestaurants': '레스토랑 찾기',
    'findRestaurantsDesc': '지도를 탐색하여 원하는 지역의 레스토랑을 찾으세요',
    'clickMarker': '마커 클릭',
    'clickMarkerDesc': '레스토랑 마커를 클릭하여 상세 정보를 확인하세요',
    'checkPayment': '결제 수단 확인',
    'checkPaymentDesc': '사용 가능한 결제 수단과 다른 사람들의 리뷰를 확인하세요',
    'writeReviewDesc': '리뷰를 작성하여 경험을 공유하세요',
    
    // Content Filtering
    'contentFilter.title': '콘텐츠 검증 결과',
    'contentFilter.violations': '발견된 문제점:',
    'contentFilter.warning': '주의사항:',
    'contentFilter.filteredText': '필터링된 텍스트:',
    'contentFilter.inappropriateLanguage': '부적절한 언어 사용',
    'contentFilter.advertising': '광고성 콘텐츠',
    'contentFilter.sensitiveTopic': '민감한 주제 언급',
    'contentFilter.spam': '스팸성 콘텐츠',
    'contentFilter.tooShort': '리뷰가 너무 짧음',
    'contentFilter.tooLong': '리뷰가 너무 김',
    'contentFilter.paymentKeywords': '결제 수단과 관련된 내용을 포함하여 작성해주세요.',
    
    // Map Controls
    'map.zoomIn': '확대',
    'map.zoomOut': '축소',
    'map.currentLocation': '현재 위치로 이동',
    'map.locationDetecting': '위치 감지 중...',
    'map.currentLocationSuccess': '현재 위치',
    'map.kyotoDefault': '교토 (기본)',
    'map.showSearchResults': '검색 결과 보기',
    'map.hideSearchResults': '검색 결과 숨기기',
    
    // Guide Page
    'guide.title': '서비스 사용가이드',
    'guide.introduction.title': '서비스 소개',
    'guide.introduction.description': 'Japan Food Web은 일본 여행 중 음식점에서 사용 가능한 결제수단을 미리 확인할 수 있는 서비스입니다. 수이카, 페이페이, 신용카드, 현금 등 다양한 결제방법 정보를 제공하여 편리한 일본 여행을 도와드립니다.',
    'guide.howToUse.title': '사용방법',
    'guide.step1.title': '음식점 검색',
    'guide.step1.description': '지도에서 원하는 지역을 찾거나 검색창에 음식점 이름을 입력하세요.',
    'guide.step1.example': '예: "라멘", "스시", "오사카 음식점"',
    'guide.step2.title': '결제수단 필터링',
    'guide.step2.description': '원하는 결제수단을 선택하여 해당 결제방법을 지원하는 음식점만 표시하세요.',
    'guide.step2.example': '예: 수이카, 페이페이, 신용카드',
    'guide.step3.title': '음식점 선택',
    'guide.step3.description': '지도나 리스트에서 원하는 음식점을 클릭하여 상세정보를 확인하세요.',
    'guide.step3.example': '결제수단, 리뷰, 평점 확인',
    'guide.step4.title': '리뷰 작성',
    'guide.step4.description': '방문한 음식점의 결제수단 정보를 다른 사용자들과 공유하세요.',
    'guide.step4.example': '익명으로 안전하게 리뷰 작성',
    'guide.features.title': '주요 기능',
    'guide.features.favorites.title': '즐겨찾기',
    'guide.features.favorites.description': '자주 가는 음식점을 즐겨찾기에 저장하여 빠르게 접근하세요.',
    'guide.features.history.title': '검색 기록',
    'guide.features.history.description': '이전 검색 기록을 확인하여 다시 찾아보세요.',
    'guide.features.payment.title': '결제수단 정보',
    'guide.features.payment.description': '실제 사용자 리뷰를 바탕으로 한 정확한 결제수단 정보를 제공합니다.',
    'guide.tips.title': '사용 팁',
    'guide.tips.tip1': '검색할 때는 음식점 이름보다는 음식 종류나 지역명으로 검색하는 것이 더 효과적입니다.',
    'guide.tips.tip2': '여러 결제수단을 선택하면 해당 결제방법들을 모두 지원하는 음식점만 표시됩니다.',
    'guide.tips.tip3': '리뷰를 작성할 때는 실제 사용한 결제수단만 선택하여 정확한 정보를 제공해주세요.',
    'guide.tips.tip4': '모바일에서는 지도를 확대/축소하여 원하는 지역을 자세히 살펴보세요.',
    'guide.contact.title': '문의하기',
    'guide.contact.description': '서비스 사용 중 궁금한 점이 있으시면 언제든지 문의해주세요.',
    'guide.contact.button': '문의하기',
    'guide.contact.start': '서비스 시작하기',
    
    // Privacy Page
    'privacy.title': '개인정보처리방침',
    'privacy.lastUpdated': '최종 업데이트',
    'privacy.introduction.title': '개인정보처리방침',
    'privacy.introduction.description': 'Japan Food Web은 사용자의 개인정보를 보호하기 위해 최선을 다하고 있습니다. 본 개인정보처리방침은 서비스 이용 시 수집되는 개인정보의 처리방법을 안내합니다.',
    'privacy.collection.title': '수집하는 정보',
    'privacy.collection.personalInfo.title': '개인정보',
    'privacy.collection.personalInfo.item1': '익명 ID (쿠키를 통한 자동 생성)',
    'privacy.collection.personalInfo.item2': '언어 설정 (선택사항)',
    'privacy.collection.personalInfo.item3': '검색 기록 (선택사항)',
    'privacy.collection.usageInfo.title': '사용 정보',
    'privacy.collection.usageInfo.item1': '음식점 검색 기록',
    'privacy.collection.usageInfo.item2': '리뷰 작성 내용',
    'privacy.collection.usageInfo.item3': '서비스 이용 통계',
    'privacy.usage.title': '정보 사용 목적',
    'privacy.usage.item1': '서비스 제공 및 개선',
    'privacy.usage.item2': '사용자 경험 향상',
    'privacy.usage.item3': '음식점 정보 제공',
    'privacy.usage.item4': '리뷰 시스템 운영',
    'privacy.usage.item5': '서비스 통계 분석',
    'privacy.protection.title': '정보 보호',
    'privacy.protection.item1': 'SSL 암호화를 통한 안전한 데이터 전송',
    'privacy.protection.item2': '익명화된 데이터만 수집 및 저장',
    'privacy.protection.item3': '개인식별정보 수집 최소화',
    'privacy.protection.item4': '정기적인 보안 점검 및 업데이트',
    'privacy.thirdParty.title': '제3자 서비스',
    'privacy.thirdParty.google.title': 'Google Maps API',
    'privacy.thirdParty.google.description': '지도 서비스 제공을 위해 Google Maps API를 사용합니다. Google의 개인정보처리방침이 적용됩니다.',
    'privacy.thirdParty.vercel.title': 'Vercel',
    'privacy.thirdParty.vercel.description': '웹사이트 호스팅을 위해 Vercel을 사용합니다. Vercel의 개인정보처리방침이 적용됩니다.',
    'privacy.thirdParty.redis.title': 'Upstash Redis',
    'privacy.thirdParty.redis.description': '리뷰 데이터 저장을 위해 Upstash Redis를 사용합니다. Upstash의 개인정보처리방침이 적용됩니다.',
    'privacy.rights.title': '사용자 권리',
    'privacy.rights.item1': '개인정보 수집 및 이용에 대한 동의 철회',
    'privacy.rights.item2': '개인정보 열람 및 정정 요청',
    'privacy.rights.item3': '개인정보 삭제 요청',
    'privacy.rights.item4': '개인정보 처리정지 요청',
    'privacy.contact.title': '문의처',
    'privacy.contact.email': '이메일',
    'privacy.contact.description': '개인정보 관련 문의사항이 있으시면 언제든지 연락해주세요.',
    'privacy.changes.title': '개인정보처리방침 변경',
    'privacy.changes.description': '개인정보처리방침은 법령, 정책 또는 보안기술의 변경에 따라 내용의 추가, 삭제 및 수정이 있을 수 있습니다. 변경사항은 웹사이트에 공지하여 안내드립니다.',
    'privacy.navigation.guide': '사용가이드',
    'privacy.navigation.contact': '문의하기',
    
    // Contact Page
    'contact.title': '문의하기',
    'contact.subtitle': '서비스 사용 중 궁금한 점이 있으시면 언제든지 문의해주세요.',
    'contact.info.title': '연락처 정보',
    'contact.info.email.title': '이메일 문의',
    'contact.info.email.description': '가장 빠르고 정확한 답변을 받을 수 있는 방법입니다.',
    'contact.info.response.title': '답변 시간',
    'contact.info.response.description': '평일 24시간 이내, 주말 48시간 이내에 답변드립니다.',
    'contact.info.hours.title': '서비스 시간',
    'contact.info.hours.description': '24시간 언제든지 문의하실 수 있습니다.',
    'contact.form.title': '문의하기',
    'contact.form.email.title': '이메일로 문의하기',
    'contact.form.email.description': '아래 버튼을 클릭하면 자동으로 이메일 작성 화면이 열립니다.',
    'contact.form.email.button': '이메일 보내기',
    'contact.form.email.sent': '이메일 앱이 열렸습니다. 문의 내용을 작성해주세요.',
    'contact.form.template.title': '문의 템플릿',
    'contact.form.template.subject': '제목',
    'contact.form.template.body': '내용',
    'contact.email.subject': '[Japan Food Web] 서비스 문의',
    'contact.email.body': '안녕하세요.\n\nJapan Food Web 서비스 이용 중 문의사항이 있어 연락드립니다.\n\n문의 유형: [버그 신고 / 기능 제안 / 기타]\n문의 내용:\n\n\n감사합니다.',
    'contact.faq.title': '자주 묻는 질문',
    'contact.faq.q1.question': 'Q. 리뷰는 누구나 작성할 수 있나요?',
    'contact.faq.q1.answer': '네, 회원가입 없이도 익명으로 리뷰를 작성할 수 있습니다. 익명 ID를 통해 안전하게 서비스를 이용하실 수 있습니다.',
    'contact.faq.q2.question': 'Q. 잘못된 정보가 있으면 어떻게 하나요?',
    'contact.faq.q2.answer': '음식점 정보에 오류가 있다면 문의하기를 통해 알려주시면 빠르게 수정하겠습니다. 또한 다른 사용자들의 리뷰를 통해 정확한 정보를 제공합니다.',
    'contact.faq.q3.question': 'Q. 모바일에서도 사용할 수 있나요?',
    'contact.faq.q3.answer': '네, 모바일 브라우저에서도 최적화된 인터페이스로 편리하게 사용하실 수 있습니다. 반응형 디자인으로 모든 기기에서 원활하게 작동합니다.',
    'contact.faq.q4.question': 'Q. 개인정보는 안전하게 보호되나요?',
    'contact.faq.q4.answer': '네, 개인식별정보는 수집하지 않으며, 익명화된 데이터만 사용합니다. SSL 암호화를 통해 안전하게 데이터를 전송하고 저장합니다.',
    'contact.navigation.guide': '사용가이드',
    'contact.navigation.privacy': '개인정보처리방침',
  },
  zh: {
    // Header
    'header.title': 'PayMap Japan',
    'header.backToHome': '返回首页',
    'header.anonymous': '匿名',
    
    // Search
    'search.placeholder': 'Search for restaurants in Japan...',
    'search.button': '搜索',
    'search.searching': '搜索中...',
    'search.clear': '清除',
    'search.clearAll': '显示原始餐厅',
    'search.info': '您可以搜索全日本的餐厅！',
    'search.examples': '示例："拉面"、"寿司"、"大阪餐厅"、"东京咖啡厅"、"京都传统美食"等',
    'search.nationwide': '搜索结果将在日本全国范围内查找。',
    
    // Filters
    'filters.paymentMethods': '支付方式',
    'filters.advanced': '高级筛选',
    'filters.sort': '排序',
    'filters.history': '历史记录',
    'filters.favorites': '收藏夹',
    'filters.clearAll': '清除所有筛选',
    'filters.active': '已激活',
    
    // Payment Methods
    'payment.selectMethods': '选择支付方式:',
    
    // Results
    'results.found': '找到 {count} 家餐厅',
    'results.showing': '显示 {count} 家餐厅',
    'results.withSelectedMethods': '使用选定的支付方式',
    'results.searchResults': '搜索结果',
    'results.restaurants': '家餐厅',
    'results.nationwideSearch': '在日本全国范围内搜索',
    'results.filteredByPayment': '按选定支付方式筛选',
    'results.backToOriginal': '返回原始餐厅',
    'results.basicRestaurants': '显示 {count} 家基本餐厅',
    
    // Restaurant Info
    'restaurant.paymentMethods': '支付方式',
    'restaurant.reviews': '评论',
    'restaurant.writeReview': '写评论',
    'restaurant.noReviews': '还没有评论。成为第一个评论者！',
    'restaurant.noReviewsMessage': '还没有注册的评论。请参与评论撰写！',
    'restaurant.noPaymentMethods': '还没有支付方式信息。添加评论以分享支付选项！',
    'restaurant.searchResult': '搜索结果',
    'restaurant.restaurant': '餐厅',
    'restaurant.city': '城市',
    
    // Reviews
    'review.sample': '示例评论 - 添加您自己的评论以分享实际支付选项！',
    'review.delete': '删除',
    'review.helpful': '👍',
    
    // Advanced Filters
    'advancedFilters.title': '高级筛选',
    'advancedFilters.priceRange': '价格范围',
    'advancedFilters.rating': '最低评分',
    'advancedFilters.distance': '距离 (公里)',
    'advancedFilters.openNow': '营业中',
    'advancedFilters.hasReviews': '有评论',
    'advancedFilters.paymentMethods': '支付方式',
    'advancedFilters.clearAll': '全部清除',
    'advancedFilters.apply': '应用筛选',
    
    // Sort Options
    'sort.title': '排序选项',
    'sort.rating': '评分',
    'sort.reviewCount': '评论数',
    'sort.distance': '距离',
    'sort.name': '名称',
    'sort.newest': '最新',
    'sort.ascending': '升序',
    'sort.descending': '降序',
    
    // Search History
    'history.title': '搜索历史',
    'history.noHistory': '还没有搜索历史',
    'history.historyDesc': '您的最近搜索将显示在这里',
    'history.recentSearches': '次最近搜索',
    'history.clearAll': '全部清除',
    'history.justNow': '刚刚',
    'history.minutesAgo': '{count} 分钟前',
    'history.hoursAgo': '{count} 小时前',
    'history.daysAgo': '{count} 天前',
    'history.locationSaved': '位置已保存',
    
    // Favorites
    'favorites.title': '我的收藏',
    'favorites.noFavorites': '还没有收藏',
    'favorites.noFavoritesDesc': '将餐厅添加到收藏夹以在此处查看',
    'favorites.view': '查看',
    'favorites.addNote': '添加备注',
    'favorites.editNote': '编辑备注',
    'favorites.save': '保存',
    'favorites.cancel': '取消',
    'favorites.noNote': '未添加备注',
    'favorites.added': '添加日期',
    'favorites.today': '今天',
    'favorites.yesterday': '昨天',
    'favorites.daysAgo': '{count} 天前',
    'favorites.clearAll': '全部清除',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.close': '关闭',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.view': '查看',
    'common.clear': '清除',
    'common.apply': '应用',
    'common.reset': '重置',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.sort': '排序',
    'common.favorites': '收藏夹',
    'common.history': '历史记录',
    'common.settings': '设置',
    'common.language': '语言',
    'common.theme': '主题',
    'common.darkMode': '深色模式',
    'common.lightMode': '浅色模式',
    'common.system': '系统',
    
    // Main page
    'paymentMethodReviewService': '支付方式评论服务',
    'discoverPaymentMethods': '发现日本餐厅的支付方式',
    'heroDescription': '在Google地图上找到餐厅，检查可用的支付方式，并与他人分享您的体验',
    'viewMap': '查看地图',
    'writeReview': '写评论',
    'mapBasedSearch': '基于地图的搜索',
    'mapBasedSearchDesc': '轻松找到您所需区域的餐厅，并在Google地图上检查它们的位置',
    'paymentMethodInfo': '支付方式信息',
    'paymentMethodInfoDesc': '一目了然地查看每家餐厅可用的支付方式',
    'realTimeReviews': '实时评论',
    'realTimeReviewsDesc': '留下关于支付方式的匿名评论，并与他人分享',
    'howToUse': '使用方法',
    'findRestaurants': '查找餐厅',
    'findRestaurantsDesc': '浏览地图以找到您所需区域的餐厅',
    'clickMarker': '点击标记',
    'clickMarkerDesc': '点击餐厅标记以查看详细信息',
    'checkPayment': '检查支付',
    'checkPaymentDesc': '查看可用的支付方式和其他人的评论',
    'writeReviewDesc': '通过写评论分享您的体验',
    
    // Content Filtering
    'contentFilter.title': '内容验证结果',
    'contentFilter.violations': '检测到的问题:',
    'contentFilter.warning': '警告:',
    'contentFilter.filteredText': '过滤后的文本:',
    'contentFilter.inappropriateLanguage': '不当语言使用',
    'contentFilter.advertising': '广告内容',
    'contentFilter.sensitiveTopic': '敏感话题提及',
    'contentFilter.spam': '垃圾内容',
    'contentFilter.tooShort': '评论太短',
    'contentFilter.tooLong': '评论太长',
    'contentFilter.paymentKeywords': '请包含与支付方式相关的内容。',
    
    // Map Controls
    'map.zoomIn': '放大',
    'map.zoomOut': '缩小',
    'map.currentLocation': '前往当前位置',
    'map.locationDetecting': '正在检测位置...',
    'map.currentLocationSuccess': '当前位置',
    'map.kyotoDefault': '京都（默认）',
    'map.showSearchResults': '显示搜索结果',
    'map.hideSearchResults': '隐藏搜索结果',
    
    // Guide Page
    'guide.title': '服务使用指南',
    'guide.introduction.title': '服务介绍',
    'guide.introduction.description': 'Japan Food Web是一个可以在日本旅行期间提前确认餐厅可用支付方式的服务。我们提供Suica、PayPay、信用卡、现金等各种支付方式的信息，帮助您享受便利的日本旅行。',
    'guide.howToUse.title': '使用方法',
    'guide.step1.title': '搜索餐厅',
    'guide.step1.description': '在地图上找到您想要的区域或在搜索框中输入餐厅名称。',
    'guide.step1.example': '例如："拉面"、"寿司"、"大阪餐厅"',
    'guide.step2.title': '支付方式筛选',
    'guide.step2.description': '选择您想要的支付方式，只显示支持该支付方式的餐厅。',
    'guide.step2.example': '例如：Suica、PayPay、信用卡',
    'guide.step3.title': '选择餐厅',
    'guide.step3.description': '从地图或列表中点击您想要的餐厅以查看详细信息。',
    'guide.step3.example': '确认支付方式、评论、评分',
    'guide.step4.title': '撰写评论',
    'guide.step4.description': '与其他用户分享您访问过的餐厅的支付方式信息。',
    'guide.step4.example': '匿名安全地撰写评论',
    'guide.features.title': '主要功能',
    'guide.features.favorites.title': '收藏夹',
    'guide.features.favorites.description': '将常去的餐厅保存到收藏夹中以便快速访问。',
    'guide.features.history.title': '搜索历史',
    'guide.features.history.description': '查看之前的搜索历史以便再次查找。',
    'guide.features.payment.title': '支付方式信息',
    'guide.features.payment.description': '基于实际用户评论提供准确的支付方式信息。',
    'guide.tips.title': '使用技巧',
    'guide.tips.tip1': '搜索时，按食物类型或地区名称搜索比按餐厅名称搜索更有效。',
    'guide.tips.tip2': '选择多种支付方式时，只会显示支持所有这些支付方式的餐厅。',
    'guide.tips.tip3': '撰写评论时，请只选择您实际使用的支付方式以提供准确信息。',
    'guide.tips.tip4': '在移动设备上，可以放大/缩小地图以详细查看您想要的区域。',
    'guide.contact.title': '联系我们',
    'guide.contact.description': '如果您在使用服务过程中有任何疑问，请随时联系我们。',
    'guide.contact.button': '联系我们',
    'guide.contact.start': '开始服务',
    
    // Privacy Page
    'privacy.title': '隐私政策',
    'privacy.lastUpdated': '最后更新',
    'privacy.introduction.title': '隐私政策',
    'privacy.introduction.description': 'Japan Food Web致力于保护用户隐私。本隐私政策说明了使用服务时收集的个人信息的处理方法。',
    'privacy.collection.title': '我们收集的信息',
    'privacy.collection.personalInfo.title': '个人信息',
    'privacy.collection.personalInfo.item1': '匿名ID（通过Cookie自动生成）',
    'privacy.collection.personalInfo.item2': '语言设置（可选）',
    'privacy.collection.personalInfo.item3': '搜索历史（可选）',
    'privacy.collection.usageInfo.title': '使用信息',
    'privacy.collection.usageInfo.item1': '餐厅搜索历史',
    'privacy.collection.usageInfo.item2': '评论内容',
    'privacy.collection.usageInfo.item3': '服务使用统计',
    'privacy.usage.title': '信息使用目的',
    'privacy.usage.item1': '服务提供和改进',
    'privacy.usage.item2': '用户体验提升',
    'privacy.usage.item3': '餐厅信息提供',
    'privacy.usage.item4': '评论系统运营',
    'privacy.usage.item5': '服务统计分析',
    'privacy.protection.title': '信息保护',
    'privacy.protection.item1': '通过SSL加密进行安全数据传输',
    'privacy.protection.item2': '仅收集和存储匿名化数据',
    'privacy.protection.item3': '最小化个人识别信息收集',
    'privacy.protection.item4': '定期安全检查和更新',
    'privacy.thirdParty.title': '第三方服务',
    'privacy.thirdParty.google.title': 'Google Maps API',
    'privacy.thirdParty.google.description': '我们使用Google Maps API提供地图服务。适用Google的隐私政策。',
    'privacy.thirdParty.vercel.title': 'Vercel',
    'privacy.thirdParty.vercel.description': '我们使用Vercel进行网站托管。适用Vercel的隐私政策。',
    'privacy.thirdParty.redis.title': 'Upstash Redis',
    'privacy.thirdParty.redis.description': '我们使用Upstash Redis存储评论数据。适用Upstash的隐私政策。',
    'privacy.rights.title': '用户权利',
    'privacy.rights.item1': '撤回个人信息收集和使用的同意',
    'privacy.rights.item2': '请求访问和更正个人信息',
    'privacy.rights.item3': '请求删除个人信息',
    'privacy.rights.item4': '请求停止个人信息处理',
    'privacy.contact.title': '联系信息',
    'privacy.contact.email': '电子邮件',
    'privacy.contact.description': '如果您对隐私有任何疑问，请随时联系我们。',
    'privacy.changes.title': '隐私政策变更',
    'privacy.changes.description': '隐私政策可能会根据法律、政策或安全技术的变化而进行添加、删除或修改。变更将在网站上公布。',
    'privacy.navigation.guide': '使用指南',
    'privacy.navigation.contact': '联系我们',
    
    // Contact Page
    'contact.title': '联系我们',
    'contact.subtitle': '如果您在使用服务过程中有任何疑问，请随时联系我们。',
    'contact.info.title': '联系信息',
    'contact.info.email.title': '邮件咨询',
    'contact.info.email.description': '这是获得最快、最准确回复的方法。',
    'contact.info.response.title': '回复时间',
    'contact.info.response.description': '我们会在工作日内24小时内、周末48小时内回复。',
    'contact.info.hours.title': '服务时间',
    'contact.info.hours.description': '您可以24小时随时联系我们。',
    'contact.form.title': '联系我们',
    'contact.form.email.title': '通过邮件联系我们',
    'contact.form.email.description': '点击下面的按钮将自动打开邮件编写界面。',
    'contact.form.email.button': '发送邮件',
    'contact.form.email.sent': '邮件应用已打开。请编写您的咨询内容。',
    'contact.form.template.title': '咨询模板',
    'contact.form.template.subject': '主题',
    'contact.form.template.body': '内容',
    'contact.email.subject': '[Japan Food Web] 服务咨询',
    'contact.email.body': '您好。\n\n我在使用Japan Food Web服务过程中有咨询事项，特此联系。\n\n咨询类型：[错误报告 / 功能建议 / 其他]\n咨询内容：\n\n\n谢谢。',
    'contact.faq.title': '常见问题',
    'contact.faq.q1.question': 'Q. 任何人都可以写评论吗？',
    'contact.faq.q1.answer': '是的，您无需注册即可匿名撰写评论。您可以通过匿名ID安全地使用服务。',
    'contact.faq.q2.question': 'Q. 如果有错误信息该怎么办？',
    'contact.faq.q2.answer': '如果餐厅信息有错误，请通过联系我们告知我们，我们会快速修复。我们还通过其他用户的评论提供准确信息。',
    'contact.faq.q3.question': 'Q. 可以在移动设备上使用吗？',
    'contact.faq.q3.answer': '是的，您可以在移动浏览器上使用优化的界面方便地使用。响应式设计确保在所有设备上都能流畅运行。',
    'contact.faq.q4.question': 'Q. 个人信息是否安全保护？',
    'contact.faq.q4.answer': '是的，我们不收集个人识别信息，只使用匿名化数据。我们通过SSL加密安全地传输和存储数据。',
    'contact.navigation.guide': '使用指南',
    'contact.navigation.privacy': '隐私政策',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  // Load language preference from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('paymap_language') as Language;
    if (savedLanguage && ['en', 'ja', 'ko', 'zh'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language preference to localStorage
  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('paymap_language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    if (!translation) {
      console.warn(`Translation key not found: ${key}`);
      return key;
    }
    return translation;
  };

  const getCurrentLanguage = () => language;

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage: handleLanguageChange,
      t,
      getCurrentLanguage
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
